table dCidades
	lineageTag: e6fd3903-3f58-4f4d-875b-eb0da27e1ada

	column IdCidade
		dataType: string
		lineageTag: 70a815f2-e64b-43b1-8732-b46f75913b9f
		summarizeBy: none
		sourceColumn: IdCidade

		annotation SummarizationSetBy = Automatic

	column NomeCidade
		dataType: string
		lineageTag: ea4ff23c-c52e-4aff-b456-21d6d4a7db6c
		summarizeBy: none
		sourceColumn: NomeCidade

		annotation SummarizationSetBy = Automatic

	column IdEstado
		dataType: string
		lineageTag: 4c610cdc-3710-49cd-8822-ff166a3050b5
		summarizeBy: none
		sourceColumn: IdEstado

		annotation SummarizationSetBy = Automatic

	column NomeEstado
		dataType: string
		lineageTag: c9d988bb-790f-466a-8e27-b351a620d4aa
		summarizeBy: none
		sourceColumn: NomeEstado

		annotation SummarizationSetBy = Automatic

	partition dCidades = m
		mode: import
		queryGroup: Dimensões
		source =
				let
				    Token = fnGetToken(),
				    BaseUrl = "https://api-service.fogocruzado.org.br",
				    Endpoint = "api/v2/cities",
				    Fonte = Json.Document(
				        Web.Contents(BaseUrl,
				            [
				                RelativePath = Endpoint,
				                Headers = [
				                    #"Authorization" = "Bearer " & Token,
				                    #"Accept" = "application/json"
				                ]
				            ]
				        )
				    ),
				    Dados = Fonte[data],
				    Tabela = Table.FromList(Dados, Splitter.SplitByNothing(), {"Registro"}),
				    CidadesExpandidas = Table.ExpandRecordColumn(Tabela, "Registro", {"id", "name", "state"}, {"IdCidade", "NomeCidade", "Estado"}),
				    EstadoExp = Table.ExpandRecordColumn(CidadesExpandidas, "Estado", {"id", "name"}, {"IdEstado", "NomeEstado"})
				in
				    EstadoExp

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

