table dHora
	lineageTag: a037f7fe-ce9d-4e80-b2ce-372438f2ef6f

	column Hora
		dataType: int64
		formatString: 0
		lineageTag: 3cb58aa0-f1ec-4eab-b8ab-2e0efdd0f801
		summarizeBy: sum
		sourceColumn: Hora

		annotation SummarizationSetBy = Automatic

	column Período
		dataType: string
		lineageTag: 2b9ae4cb-1c51-4e65-8804-8bc754b19a29
		summarizeBy: none
		sourceColumn: Período

		annotation SummarizationSetBy = Automatic

	column Ordem_Período
		dataType: int64
		formatString: 0
		lineageTag: fd96ef06-ccda-4d61-8fb0-dcba2b74e311
		summarizeBy: sum
		sourceColumn: Ordem_Período

		annotation SummarizationSetBy = Automatic

	column AMPM
		dataType: string
		lineageTag: ca0566b2-9be5-4f92-a565-6f2031908214
		summarizeBy: none
		sourceColumn: AMPM

		annotation SummarizationSetBy = Automatic

	column 'Hora AMPM'
		dataType: string
		lineageTag: 09b00434-581f-4c41-893b-9ea4221584d7
		summarizeBy: none
		sourceColumn: Hora AMPM

		annotation SummarizationSetBy = Automatic

	column Hora_extenso
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5da9ca42-c858-488f-bb15-816ba0360f9c
		summarizeBy: none
		sourceColumn: Hora_extenso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition dHora = m
		mode: import
		queryGroup: Dimensões
		source = ```
				let
				    // Cria uma tabela com as horas do dia
				    tabelaHora = Table.FromColumns({{0 .. 23}}, {"Hora"}),
				
				    // Adiciona coluna "Período"
				    tabelaHoraComPeriodo = Table.AddColumn(
				        tabelaHora,
				        "Período",
				        each if [Hora] < 12 then "Manhã" 
				             else if [Hora] < 18 then "Tarde" 
				             else "Noite"
				    ),
				
				    // Adiciona coluna auxiliar para ordenar o período
				    adicionarOrdemPeriodo = Table.AddColumn(
				        tabelaHoraComPeriodo,
				        "Ordem_Período",
				        each if [Período] = "Manhã" then 1 
				             else if [Período] = "Tarde" then 2 
				             else 3,
				        Int64.Type
				    ),
				
				    // Adiciona AM/PM
				    AMPM = Table.AddColumn(
				        adicionarOrdemPeriodo,
				        "AMPM",
				        each if [Hora] < 12 then "AM" else "PM",
				        type text
				    ),
				
				    // Hora no formato 12h (com AM/PM)
				    HoraAMPM = Table.AddColumn(
				        AMPM,
				        "Hora AMPM",
				        each
				            if [Hora] = 0 then "12 AM"
				            else if [Hora] >= 1 and [Hora] <= 11 then Number.ToText([Hora]) & " AM"
				            else if [Hora] = 12 then "12 PM"
				            else if [Hora] >= 13 then Number.ToText([Hora] - 12) & " PM"
				            else "Unknown",
				        type text
				    ),
				
				    // Hora por extenso (texto tipo “00:00”, “13:00”)
				    HoraExtenso = Table.AddColumn(
				        HoraAMPM,
				        "Hora_extenso",
				        each Text.PadStart(Text.From([Hora]), 2, "0") & ":00",
				        type text
				    ),
				
				    // Garante tipos corretos
				    tipandocolunas = Table.TransformColumnTypes(
				        HoraExtenso,
				        {
				            {"Hora", Int64.Type},
				            {"Período", type text},
				            {"Ordem_Período", Int64.Type},
				            {"AMPM", type text},
				            {"Hora AMPM", type text},
				            {"Hora_extenso", type text}
				        }
				    ),
				
				    // Ordena por Período e Hora
				    ordenar = Table.Sort(tipandocolunas, {{"Ordem_Período", Order.Ascending}, {"Hora", Order.Ascending}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(ordenar,{{"Hora_extenso", type time}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

