table fOcorrencias
	lineageTag: a3a1b150-8df9-403e-a1a7-a61b19737976

	column Id
		dataType: string
		lineageTag: 0ecf4df8-bd87-47e3-b566-6dbf931b7cac
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Documento
		dataType: int64
		formatString: 0
		lineageTag: 75ceb555-0e06-410a-a478-a5f139573286
		summarizeBy: sum
		sourceColumn: Documento

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 873c637d-f000-4730-97dc-5e980be3ec88
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hora
		dataType: dateTime
		formatString: Long Time
		lineageTag: dc48f7d0-8be9-49db-9c2f-f345a742ddd2
		summarizeBy: none
		sourceColumn: Hora

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Estado
		dataType: string
		lineageTag: 3aa87762-c4c7-4f56-af15-ce040a5d004d
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 14f1a82a-6c45-4540-8d1b-d94d159db171
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Bairro
		dataType: string
		lineageTag: ca540cd4-1f06-48db-8807-6d8fdafed3f6
		summarizeBy: none
		sourceColumn: Bairro

		annotation SummarizationSetBy = Automatic

	column Motivo
		dataType: string
		lineageTag: ff50c882-6785-47bb-8bad-c40987d72355
		summarizeBy: none
		sourceColumn: Motivo

		annotation SummarizationSetBy = Automatic

	column Endereco
		dataType: string
		lineageTag: 6fbf6448-9aaa-435b-aa9c-18f6c4426420
		summarizeBy: none
		sourceColumn: Endereco

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: string
		lineageTag: 6905ca9c-ff4e-4219-9af9-f4154d55a8e8
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

	column Longitude
		dataType: string
		lineageTag: 0ea12a22-cd5d-4edf-8e81-0faf06612423
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

	column AcaoPolicial
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 28f6be59-726b-4428-964e-c1176b9ce9d4
		summarizeBy: none
		sourceColumn: AcaoPolicial

		annotation SummarizationSetBy = Automatic

	column PresencaAgente
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 15ea84d7-b726-4736-ba11-c8ae03e8ba32
		summarizeBy: none
		sourceColumn: PresencaAgente

		annotation SummarizationSetBy = Automatic

	partition fOcorrencias = m
		mode: import
		queryGroup: Fato
		source =
				let
				    // Token da função de autenticação
				    Token = fnGetToken(),
				
				    // Configuração base da API
				    BaseUrl = "https://api-service.fogocruzado.org.br",
				    IdEstado_RJ = "b112ffbe-17b3-4ad0-8f2a-2038745d1d14",
				    ItensPorPagina = 200,
				
				    // Função que retorna uma página da API com seus dados
				    GetPage = (Pagina as number) =>
				        let
				            Endpoint =
				                "api/v2/occurrences?"
				                & "idState=" & IdEstado_RJ
				                & "&order=ASC"
				                & "&page=" & Number.ToText(Pagina)
				                & "&take=" & Number.ToText(ItensPorPagina),
				
				            Fonte = Json.Document(
				                Web.Contents(
				                    BaseUrl,
				                    [
				                        RelativePath = Endpoint,
				                        Headers = [
				                            #"Authorization" = "Bearer " & Token,
				                            #"Accept" = "application/json"
				                        ]
				                    ]
				                )
				            ),
				
				            Dados = Fonte[data],
				            Meta = Fonte[pageMeta],
				            ProximaPagina = if Meta[hasNextPage] then Pagina + 1 else null
				        in
				            [Dados = Dados, Proxima = ProximaPagina],
				
				    // Paginação dinâmica: carrega até acabar os dados
				    TodasAsPaginas =
				        List.Generate(
				            () => GetPage(1),
				            each [Dados] <> null and List.Count([Dados]) > 0,
				            each if [Proxima] <> null then GetPage([Proxima]) else [Dados = {}, Proxima = null],
				            each [Dados]
				        ),
				
				    // Combina todas as páginas em uma única lista
				    ListaFinal = List.Combine(TodasAsPaginas),
				
				    // Converte lista em tabela
				    Tabela = Table.FromList(ListaFinal, Splitter.SplitByNothing(), {"Registro"}),
				
				    // Expande os campos principais da ocorrência
				    Expandido = Table.ExpandRecordColumn(
				        Tabela, "Registro",
				        {"id", "documentNumber", "address", "date", "state", "city", "neighborhood", "contextInfo", "latitude", "longitude", "policeAction", "agentPresence"},
				        {"Id", "Documento", "Endereco", "DataHora", "Estado", "Cidade", "Bairro", "Contexto", "Latitude", "Longitude", "AcaoPolicial", "PresencaAgente"}
				    ),
				
				    ExpEstado = Table.ExpandRecordColumn(Expandido, "Estado", {"name"}, {"Estado"}),
				    ExpCidade = Table.ExpandRecordColumn(ExpEstado, "Cidade", {"name"}, {"Cidade"}),
				    ExpBairro = Table.ExpandRecordColumn(ExpCidade, "Bairro", {"name"}, {"Bairro"}),
				    ExpMotivo = Table.ExpandRecordColumn(ExpBairro, "Contexto", {"mainReason"}, {"MotivoPrincipal"}),
				    ExpMotivoFinal = Table.ExpandRecordColumn(ExpMotivo, "MotivoPrincipal", {"name"}, {"Motivo"}),
				
				    // Conversão de tipos com tratamento de campos nulos
				    Tipos = Table.TransformColumnTypes(ExpMotivoFinal, {
				        {"Id", type text},
				        {"Documento", Int64.Type},
				        {"Endereco", type text},
				        {"DataHora", type datetime},
				        {"Estado", type text},
				        {"Cidade", type text},
				        {"Bairro", type text},
				        {"Motivo", type text},
				        {"Latitude", type nullable text},
				        {"Longitude", type nullable text},
				        {"AcaoPolicial", type nullable logical},
				        {"PresencaAgente", type nullable logical}
				    }),
				
				    // Separação de data e hora
				    DataHoraTexto = Table.TransformColumnTypes(Tipos, {{"DataHora", type text}}, "pt-BR"),
				    Dividido = Table.SplitColumn(DataHoraTexto, "DataHora", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Data", "Hora"}),
				
				    // Tipagem final
				    TiposFinais = Table.TransformColumnTypes(Dividido, {
				        {"Data", type date},
				        {"Hora", type time}
				    }),
				    InicioHora = Table.TransformColumns(TiposFinais,{{"Hora", Time.StartOfHour, type time}})
				in
				    InicioHora

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

