table Medidas
	lineageTag: cdf5fd1f-deec-4e85-8eec-226144f72b1c

	/// 
	/// COUNTROWS(fOcorrencias)
	/// 
	measure 'Total Ocorrências' =
			
			COUNTROWS ( fOcorrencias )
		formatString: #,0
		displayFolder: 01. Visão Geral
		lineageTag: 0f3935b4-8c18-4431-91e2-632e96cd6125

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// NOT ISBLANK(fOcorrencias[Motivo])
	/// )
	/// 
	measure 'Total por Motivo' =
			
			CALCULATE ( [Total Ocorrências], NOT ISBLANK ( fOcorrencias[Motivo] ) )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 39d495a5-8d3b-4198-857f-1380052eb199

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// fOcorrencias[Motivo] = "Ação policial"
	/// )
	/// 
	measure 'Total Ação Policial' =
			
			CALCULATE ( [Total Ocorrências], fOcorrencias[Motivo] = "Ação policial" )
		formatString: #,0
		displayFolder: 01. Visão Geral
		lineageTag: 881ead03-8401-458a-b9bd-c6f803c1b5e3

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// fOcorrencias[Motivo] = "Operação policial"
	/// )
	/// 
	measure 'Total Operação Policial' =
			
			CALCULATE ( [Total Ocorrências], fOcorrencias[Motivo] = "Operação policial" )
		formatString: #,0
		displayFolder: 03. Contexto
		lineageTag: a914a41e-d0b4-42a0-ac53-2bd59bf63127

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// fOcorrencias[Motivo] = "Homicidio/Tentativa"
	/// )
	/// 
	measure 'Total Homicidio/Tentativa' =
			
			CALCULATE ( [Total Ocorrências], fOcorrencias[Motivo] = "Homicidio/Tentativa" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 010acb87-4b08-42e4-991e-d0d973f58756

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// fOcorrencias[Motivo] = "Tentativa/Roubo"
	/// )
	/// 
	measure 'Total Tentativa/Roubo' =
			
			CALCULATE ( [Total Ocorrências], fOcorrencias[Motivo] = "Tentativa/Roubo" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 14fba0db-1cf5-45c7-afb7-b4a01a269bc6

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// fOcorrencias[Motivo] = "Briga"
	/// )
	/// 
	measure 'Total Briga' =
			
			CALCULATE ( [Total Ocorrências], fOcorrencias[Motivo] = "Briga" )
		formatString: #,0
		displayFolder: 03. Contexto
		lineageTag: 13a8e7cb-bcf7-4f1b-854c-b4eefc86937e

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// fOcorrencias[Motivo] = "Suicídio"
	/// )
	/// 
	measure 'Total Suicídio' =
			
			CALCULATE ( [Total Ocorrências], fOcorrencias[Motivo] = "Suicídio" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 5dffedb4-38b7-47c2-8a08-5c7922bb27d1

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// dCidades[NomeEstado]="Rio de Janeiro"
	/// )
	/// 
	measure 'Total Ocorrências RJ' =
			
			CALCULATE ( [Total Ocorrências], dCidades[NomeEstado] = "Rio de Janeiro" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: c4b23ddb-4b22-4844-8864-6731808a87df

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// dCidades[NomeEstado]="Pernambuco"
	/// )
	/// 
	measure 'Total Ocorrências PE' =
			
			CALCULATE ( [Total Ocorrências], dCidades[NomeEstado] = "Pernambuco" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 4fed8065-f8b4-4b6a-8891-e637ae8d3479

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// dCidades[NomeEstado]="Bahia"
	/// )
	/// 
	measure 'Total Ocorrências BA' =
			
			CALCULATE ( [Total Ocorrências], dCidades[NomeEstado] = "Bahia" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 98c3c7fd-690a-41f2-8ebf-8a7afe8d44c1

	/// 
	/// CALCULATE(
	/// [Total Ocorrências],
	/// dCidades[NomeEstado]="Pará"
	/// )
	/// 
	measure 'Total Ocorrências PA' =
			
			CALCULATE ( [Total Ocorrências], dCidades[NomeEstado] = "Pará" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: fd1633dd-9daf-4a28-ae54-1a62ec423073

	/// 
	/// CALCULATE(
	/// COUNTROWS(fPerfilVitimas),
	/// dSituacao[Situacao] = "Dead"
	/// )
	/// 
	measure 'Total Mortes' =
			
			CALCULATE ( COUNTROWS ( fPerfilVitimas ), dSituacao[Situacao] = "Dead" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 23e19c34-2933-4197-81e5-c7ba4bbef337

	/// 
	/// CALCULATE(
	/// [Total Mortes],
	/// dPessoas[TipoPessoa_ptbr] = "Civil"
	/// )
	/// 
	measure 'Total Civis Mortos' =
			
			CALCULATE ( [Total Mortes], dPessoas[TipoPessoa_ptbr] = "Civil" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 0fb7fc47-0fd1-477a-8b96-b6f4c3529ff2

	/// 
	/// CALCULATE(
	/// [Total Mortes],
	/// dPessoas[TipoPessoa] = "Agent"
	/// )
	/// 
	measure 'Total Agentes Mortos' =
			
			CALCULATE ( [Total Mortes], dPessoas[TipoPessoa] = "Agent" )
		formatString: #,0
		displayFolder: 01. Visão Geral
		lineageTag: e7660680-54c3-4043-8cbe-b07ad106c18b

	/// 
	/// CALCULATE(
	/// [Total Mortes],
	/// fPerfilVitimas[Genero] = "Mulher Cis"
	/// )
	/// 
	measure 'Total Mulheres Mortas' =
			
			CALCULATE ( [Total Mortes], fPerfilVitimas[Genero] = "Mulher Cis" )
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: c9cf4a7e-8c79-45e6-9d49-fe9294898cdc

	/// 
	/// DIVIDE(
	/// CALCULATE(
	/// [Total Mortes],
	/// fPerfilVitimas[Genero] = "Feminino"
	/// ),
	/// [Total Mortes]
	/// )
	/// 
	measure '% Mulheres Mortas' =
			
			DIVIDE (
			    CALCULATE ( [Total Mortes], fPerfilVitimas[Genero] = "Feminino" ),
			    [Total Mortes]
			)
		displayFolder: 02. Perfil Vitima
		lineageTag: 3ccb7f73-314e-47fa-b26f-26cb17035679

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// 
	/// DIVIDE(
	/// CALCULATE(
	/// [Total Mortes],
	/// dFaixaEtarias[FaixaEtaria] IN { "Criança", "Adolescente" }
	/// ),
	/// [Total Mortes]
	/// )
	/// 
	measure '% Crianças e Adolescentes Mortos' =
			
			DIVIDE (
			    CALCULATE (
			        [Total Mortes],
			        dFaixaEtarias[FaixaEtaria] IN { "Criança", "Adolescente" }
			    ),
			    [Total Mortes]
			)
		displayFolder: 02. Perfil Vitima
		lineageTag: ad136aff-3675-490b-884f-1a48d4f41c58

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// 
	/// CALCULATE(
	/// [Total Mortes],
	/// ALLEXCEPT(fPerfilVitimas, fPerfilVitimas[Genero])
	/// )
	/// 
	measure 'Mortes por Gênero' =
			
			CALCULATE (
			    [Total Mortes],
			    ALLEXCEPT ( fPerfilVitimas, fPerfilVitimas[Genero] )
			)
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: bd6a73bb-7f98-4d4d-9e1d-5cd249c26c91

	/// 
	/// CALCULATE(
	/// [Total Mortes],
	/// ALLEXCEPT(fPerfilVitimas, dFaixaEtarias[FaixaEtaria])
	/// )
	/// 
	measure 'Mortes por Faixa Etária' =
			
			CALCULATE (
			    [Total Mortes],
			    ALLEXCEPT ( fPerfilVitimas, dFaixaEtarias[FaixaEtaria] )
			)
		formatString: #,0
		displayFolder: 02. Perfil Vitima
		lineageTag: 0294fad9-c455-40d4-9cb9-6d0409f52ee4

	/// 
	/// CALCULATE(
	/// [Total Mortes],
	/// ALLEXCEPT(fOcorrencias, fOcorrencias[Motivo])
	/// )
	/// 
	measure 'Mortes por Motivo' =
			
			CALCULATE ( [Total Mortes], ALLEXCEPT ( fOcorrencias, fOcorrencias[Motivo] ) )
		formatString: #,0
		displayFolder: 03. Contexto
		lineageTag: 733f0007-a709-4135-afc0-79cbe12a4f8e

	/// 
	/// DIVIDE(
	/// [Total Civis Mortos],
	/// [Total Agentes Mortos]
	/// )
	/// 
	measure 'Razão Civis/Agentes' =
			
			DIVIDE ( [Total Civis Mortos], [Total Agentes Mortos] )
		displayFolder: 03. Contexto
		lineageTag: f7701185-2921-49ce-b6e5-1b3ab2a7d9c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// 
	/// DIVIDE(
	/// CALCULATE(
	/// COUNTROWS(fOcorrencias),
	/// fOcorrencias[Motivo] = "Operação Policial"
	/// ),
	/// [Total Ocorrências]
	/// )
	/// 
	measure '% Ocorrências de Operação Policial' =
			
			DIVIDE (
			    CALCULATE (
			        COUNTROWS ( fOcorrencias ),
			        fOcorrencias[Motivo] = "Operação Policial"
			    ),
			    [Total Ocorrências]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: 03. Contexto
		lineageTag: 8096cdea-597f-4352-a718-1ee0a4861321

	/// 
	/// MAX('Última Atualização'[Última atualização])
	/// 
	measure Atualização =
			
			"Última Atualização: "
			    & MAX ( 'Última Atualização'[Última atualização] ) - TIME ( 3, 0, 0 )
		displayFolder: 04. Aux
		lineageTag: 4429988e-9418-4b84-b4cf-4c92a5002586

	measure 'Total Vítimas' =
			
			COUNTROWS ( fPerfilVitimas )
		formatString: 0
		lineageTag: 55cfadda-43e9-45a6-954e-070e89122b2e

	measure 'contador aux' =
			
			COUNTROWS ( fOcorrencias )
		formatString: 0
		lineageTag: 518d53b0-c960-466e-bb41-0ec7f2a5f540

	measure 'Total Ocorrências A.A' =
			
			CALCULATE (
			    COUNTROWS ( fOcorrencias ),
			    SAMEPERIODLASTYEAR ( dCalendario[Data] )
			)
		formatString: 0
		lineageTag: 2d09044f-8d64-4b41-be62-f2b1a3a6f821

	measure '% Diferença Ocorrências vs A.A' =
			
			VAR Atual = [Total Ocorrências]
			VAR AnoAnterior = [Total Ocorrências A.A]
			RETURN
			    DIVIDE ( Atual - AnoAnterior, AnoAnterior, 0 )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 41c159d8-3483-4523-ab26-53a7ad900bbd

	measure 'Total Vítimas A.A' =
			
			CALCULATE (
			    COUNTROWS ( fPerfilVitimas ),
			    SAMEPERIODLASTYEAR ( dCalendario[Data] )
			)
		formatString: 0
		lineageTag: 7bb98da2-527f-4764-ac2f-7a3ca9f520c2

	measure '% Diferença Vitimas vs A.A' =
			
			VAR Atual = [Total Vítimas]
			VAR AnoAnterior = [Total Vítimas A.A]
			RETURN
			    DIVIDE ( Atual - AnoAnterior, AnoAnterior, 0 )
		lineageTag: 4ebaf32f-800c-4f09-9771-cec11d56c689

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Mortes A.A' =
			
			CALCULATE ( [Total Mortes], SAMEPERIODLASTYEAR ( dCalendario[Data] ) )
		formatString: 0
		lineageTag: 65a4d76a-9764-4426-a8b1-95b8b2c88003

	measure '% Diferença Mortes vs A.A' =
			
			VAR Atual = [Total Mortes]
			VAR AnoAnterior = [Total Mortes A.A]
			RETURN
			    DIVIDE ( Atual - AnoAnterior, AnoAnterior, 0 )
		lineageTag: f75285e9-db97-42be-8555-c7784ac33eee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Diferença Ocorrências vs A.A Seta' =
			
			VAR vDiferenca =
			    DIVIDE (
			        [Total Ocorrências] - [Total Ocorrências A.A],
			        [Total Ocorrências A.A]
			    )
			RETURN
			    SWITCH (
			        TRUE (),
			        vDiferenca > 0, "▲ " & FORMAT ( vDiferenca, "0.00%" ),
			        vDiferenca < 0, "▼ " & FORMAT ( vDiferenca, "0.00%" ),
			        "0.00%"
			    )
		lineageTag: 4f1d9f78-175c-4eda-833e-fbbf5f4fdc2d

	measure '% Diferença Vitimas vs A.A Seta' =
			
			VAR vDiferenca = [% Diferença Vitimas vs A.A]
			RETURN
			    SWITCH (
			        TRUE (),
			        vDiferenca > 0, "▲ " & FORMAT ( vDiferenca, "0.00%" ),
			        vDiferenca < 0, "▼ " & FORMAT ( vDiferenca, "0.00%" ),
			        "0.00%"
			    )
		lineageTag: 5f0f0c36-a092-48a8-ae0a-cc49170279ab

	measure '% Diferença Mortes vs A.A Seta' =
			
			VAR vDiferenca = [% Diferença Mortes vs A.A]
			RETURN
			    SWITCH (
			        TRUE (),
			        vDiferenca > 0, "▲ " & FORMAT ( vDiferenca, "0.00%" ),
			        vDiferenca < 0, "▼ " & FORMAT ( vDiferenca, "0.00%" ),
			        "0.00%"
			    )
		lineageTag: a6236abb-59a4-493e-8e39-aa666b1ef9c5

	measure 'Total Operação com Agentes Seg. Público' =
			
			CALCULATE ( [Total Ocorrências], fOcorrencias[PresencaAgente] = TRUE () )
		formatString: 0
		lineageTag: 1e5ef40a-e595-4ffd-b59b-73dc97e105d8

	measure '% Ocorrencias com Agentes de Seg Público' =
			
			DIVIDE ( [Total Operação com Agentes Seg. Público], [Total Ocorrências] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 264d33c9-90a0-49e8-a165-3a241c730691

	measure '% Letalidade' =
			
			DIVIDE ( [Total Mortes], [Total Vítimas] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 71f7f9c0-6ee6-4e75-887b-c3c8444c5068

	measure 'Vítimas por Ocorrência' =
			
			DIVIDE ( [Total Vítimas], [Total Ocorrências] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2617d549-8ef8-448a-b11f-9a5c14e9e0e4

	measure Medida
		lineageTag: e5a68f3e-2c7e-4d18-8013-fcb6eb0ae01f

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Mortes por Ocorrência' =
			
			DIVIDE ( [Total Mortes], [Total Ocorrências] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4c0760c0-b46e-4e2e-a321-58a447c1a181

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WUlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Fonte,{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

